INDEPENDENT = 'neither'
DEMOCRAT = 'democrat'
REPUBLICAN = 'republican'

PARTY_MAPPINGS = {
    '(write-in)': INDEPENDENT,
    'aaron lee childress "skeet"': None,
    'acn': INDEPENDENT,
    'adp': INDEPENDENT,
    'ai': INDEPENDENT,
    'allen hoenicke': None,
    'amc': INDEPENDENT,
    'amd': INDEPENDENT,
    'ame': INDEPENDENT,
    'america first party': INDEPENDENT,
    "america's independent": INDEPENDENT,
    "america's party": INDEPENDENT,
    'american constitution': INDEPENDENT,
    'american constitution party': INDEPENDENT,
    'american delta': INDEPENDENT,
    'american delta party': INDEPENDENT,
    'american solidarity party': INDEPENDENT,
    'american third position': INDEPENDENT,
    'amh': INDEPENDENT,
    'amr': INDEPENDENT,
    'angelia stinnett': None,
    'anti-bushist candidate': None,
    'approval voting party': INDEPENDENT,
    'bart rowland': None,
    'basil marceaux': None,
    'bet': INDEPENDENT,
    'better for america party': INDEPENDENT,
    'bfa': INDEPENDENT,
    'bla': INDEPENDENT,
    'bob quast for term limits': None,
    'boston tea': INDEPENDENT,
    'c': INDEPENDENT,
    'charles e. drew': None,
    'cheap renewable energy': INDEPENDENT,
    'chris polsen': None,
    'christopher schappert': None,
    'cnl': INDEPENDENT,
    'colorado reform': INDEPENDENT,
    'con': INDEPENDENT,
    'con.': INDEPENDENT,
    'concerns of people': INDEPENDENT,
    'constitution': INDEPENDENT,
    'constitution party': INDEPENDENT,
    'cp': INDEPENDENT,
    'cst': INDEPENDENT,
    'd': DEMOCRAT,
    'dem': DEMOCRAT,
    'dem.': DEMOCRAT,
    'dem. wi': DEMOCRAT,
    'dem/rep': None,
    'democrat': DEMOCRAT,
    'democratic': DEMOCRAT,
    'democratic / working family': DEMOCRAT,
    'democratic party': DEMOCRAT,
    'democratic/progressive': DEMOCRAT,
    'democratic/republican': DEMOCRAT,
    'dfl': INDEPENDENT,
    'donald trump': None,
    'energy independence': INDEPENDENT,
    'evan mcmullin': None,
    'for your town': INDEPENDENT,
    'g': INDEPENDENT,
    'gary gene davis': None,
    'gary johnson': None,
    'glc': INDEPENDENT,
    'gop': REPUBLICAN,
    'gp': INDEPENDENT,
    'gre': INDEPENDENT,
    'green': INDEPENDENT,
    'green / democratic': INDEPENDENT,
    'green party': INDEPENDENT,
    'green-rainbow': INDEPENDENT,
    'grn': INDEPENDENT,
    'harold "hal" rogers': None,
    "heartquake '08": INDEPENDENT,
    'herbert a. bass': None,
    'hillary clinton': None,
    'hubert collins': None,
    'i': INDEPENDENT,
    'ind': INDEPENDENT,
    'ind.': INDEPENDENT,
    'ind. wi': INDEPENDENT,
    'independance party': INDEPENDENT,
    'independence party o': INDEPENDENT,
    'independent': INDEPENDENT,
    'independent / republican': INDEPENDENT,
    'independent american': INDEPENDENT,
    'independent american party': INDEPENDENT,
    'independent democrat': INDEPENDENT,
    'independent gop': INDEPENDENT,
    'independent party': INDEPENDENT,
    'independent people of colorado': INDEPENDENT,
    'independent progressive': INDEPENDENT,
    'independent republican': INDEPENDENT,
    'inp': INDEPENDENT,
    'inr': INDEPENDENT,
    'inter. 3rd party': INDEPENDENT,
    'iowa green party': INDEPENDENT,
    'iowa party': INDEPENDENT,
    'ip': INDEPENDENT,
    'ipl': INDEPENDENT,
    'ipo': INDEPENDENT,
    'jacob maurer': None,
    'james a. harrell': None,
    'james e. travis, jr.': None,
    'james hart': None,
    'james lee': None,
    'jason scott moore': None,
    'jill stein': None,
    'jim gray': None,
    'jim maynard': None,
    'june griffin': None,
    'jus': INDEPENDENT,
    'justice': INDEPENDENT,
    'justice party': INDEPENDENT,
    'kimberlee e. smith': None,
    'kotlikoff for president': None,
    'l': INDEPENDENT,
    'lady j jean howard-hill': None,
    'larry crim': None,
    'lbt': INDEPENDENT,
    'lee stewart': None,
    'leslie j. stith': None,
    'lib': INDEPENDENT,
    'lib.': INDEPENDENT,
    'liberatrian': INDEPENDENT,
    'libertarian': INDEPENDENT,
    'libertarian party': INDEPENDENT,
    'liberty union': INDEPENDENT,
    'lmn': INDEPENDENT,
    'louie e. johnston jr.': None,
    'margie nell penn': None,
    'marijuana': INDEPENDENT,
    'mary d. wright': None,
    'melanie hollis': None,
    'michael h. thompson': None,
    'mike warner': None,
    'moderate': INDEPENDENT,
    'n': INDEPENDENT,
    'na': INDEPENDENT,
    'nat': INDEPENDENT,
    'nat.': INDEPENDENT,
    'nav': INDEPENDENT,
    'new independent party iowa': INDEPENDENT,
    'nlp': INDEPENDENT,
    'non': INDEPENDENT,
    'non partisan': INDEPENDENT,
    'non-partisan': INDEPENDENT,
    'none': INDEPENDENT,
    'nonviolent resistance/pacifist': INDEPENDENT,
    'nopty': INDEPENDENT,
    'npa': INDEPENDENT,
    'nr': INDEPENDENT,
    'nutrition party': INDEPENDENT,
    'o': INDEPENDENT,
    'objectivist': INDEPENDENT,
    'objectivist party': INDEPENDENT,
    'open party': INDEPENDENT,
    'oth': INDEPENDENT,
    'other': INDEPENDENT,
    'pac': INDEPENDENT,
    'pcg': INDEPENDENT,
    'peace and freedom': INDEPENDENT,
    'peace and prosperity': INDEPENDENT,
    'pet': INDEPENDENT,
    'petitioning candidate': INDEPENDENT,
    'pg': INDEPENDENT,
    'pgp': INDEPENDENT,
    'pirate': INDEPENDENT,
    'pr': INDEPENDENT,
    'prg': INDEPENDENT,
    'pro': INDEPENDENT,
    'prog': INDEPENDENT,
    'progressive': INDEPENDENT,
    'progressive/democratic': INDEPENDENT,
    'prohibition': INDEPENDENT,
    'prohibition party': INDEPENDENT,
    'r': REPUBLICAN,
    'rachel robinson': None,
    'rand paul': None,
    'ray jones': None,
    'rebpulican/libertarian': INDEPENDENT,
    'ref': INDEPENDENT,
    'ref.': INDEPENDENT,
    'reform': INDEPENDENT,
    'rep': REPUBLICAN,
    'rep.': REPUBLICAN,
    'republican': REPUBLICAN,
    'republican party': REPUBLICAN,
    'richard hall': None,
    'rocky roque de la fuente': None,
    'rosalind kurita': None,
    'rr': INDEPENDENT,
    's. brett guthrie': None,
    'sean puckett': None,
    'socialism & liberation': INDEPENDENT,
    'socialism and liberation': INDEPENDENT,
    'socialist equality': INDEPENDENT,
    'socialist equality party': INDEPENDENT,
    'socialist party': INDEPENDENT,
    'socialist party usa': INDEPENDENT,
    'socialist workers': INDEPENDENT,
    'socialist workers party': INDEPENDENT,
    'socialist, usa': INDEPENDENT,
    'states no party preference': INDEPENDENT,
    'stephen l. meredith': None,
    'swp': INDEPENDENT,
    'tea party': INDEPENDENT,
    'teresa christie': None,
    'the bottom line party': INDEPENDENT,
    'thomas f. kovach': None,
    'timesizing not downsizing': INDEPENDENT,
    'timothy b. mcdonald': None,
    'total': None,
    'turtle': INDEPENDENT,
    'u.s. marijuana': INDEPENDENT,
    'u.s. pacifist': INDEPENDENT,
    'una': INDEPENDENT,
    'unaffiliated': INDEPENDENT,
    'unaffiliated / libertarian': INDEPENDENT,
    'unaffiliated / republican': INDEPENDENT,
    'unc': INDEPENDENT,
    'unenrolled': INDEPENDENT,
    'uni': INDEPENDENT,
    'united independent': INDEPENDENT,
    'united states marijuana': INDEPENDENT,
    'unity': INDEPENDENT,
    'unity party of colorado': INDEPENDENT,
    'unknown': INDEPENDENT,
    'ust': INDEPENDENT,
    'ust.': INDEPENDENT,
    'vermont politically incorrect': INDEPENDENT,
    'veterans party of america': INDEPENDENT,
    'votekiss': INDEPENDENT,
    'w/i': INDEPENDENT,
    'w/i ind': INDEPENDENT,
    'wcp': INDEPENDENT,
    'we the people': INDEPENDENT,
    'wf': INDEPENDENT,
    'wfm': INDEPENDENT,
    'wfp': INDEPENDENT,
    'wfw': INDEPENDENT,
    'wi': INDEPENDENT,
    'william scott wells': INDEPENDENT,
    'workers world': INDEPENDENT,
    'working families party': INDEPENDENT,
    'wri': INDEPENDENT,
    'write - in': INDEPENDENT,
    'write in': INDEPENDENT,
    'write-in': INDEPENDENT,
    'write-ins': INDEPENDENT,
}
